apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: blockchainminer
  name: blockchainminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blockchainminer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: blockchainminer
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          value: mongo-mongodb
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-mongodb
              key: mongodb-root-password
        image: rlkamradt/blockchainminer:1.0-SNAPSHOT
        imagePullPolicy: ""
        name: blockchainminer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
